sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: abc123
  alioss:
    endpoint: test
    access-key-id: test
    access-key-secret: test
    bucket-name: /home/embrace/source_save_path/
